// Generated by CIRCT firtool-1.139.0
module Counter(
  input clock,
        reset
);

  reg  [15:0] counter;
  reg         hasBeenResetReg;
  initial
    hasBeenResetReg = 1'bx;
  wire        _GEN = ~(hasBeenResetReg === 1'h1 & reset === 1'h0);
  assert property (@(posedge clock) disable iff (_GEN) counter < 16'h2);
  assume property (@(posedge clock) disable iff (_GEN) counter < 16'h5B);
  always @(posedge clock) begin
    if (reset) begin
      hasBeenResetReg <= 1'h1;
      counter <= 16'h0;
    end
    else
      counter <= counter + 16'h1;
  end // always @(posedge)
endmodule

